language: node_js
node_js:
  - '7.5'
cache:
  yarn: true
  directories:
    - node_modules
    - elm-stuff/build-artifacts
    - tests/elm/elm-stuff/build-artifacts
branches:
  only:
    - master
before_install:
  - rvm install 2.4.0
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn
  - $(npm bin)/bower install
  - bundle install --jobs=3 --retry=3 --deployment
script:
  - npm run test
  - npm run dist
after_success: test $TRAVIS_PULL_REQUEST == 'false' && test $TRAVIS_BRANCH == 'master' && bin/deploy
env:
  global:
    secure: Nzcx0q8WGAKiVGDlCs3smE5ujLk/jHsjnJ4gHKPDGPfReVNaQ63cXXTVjLRuJtUY1EmdUfVVXFqSKCXaKiyZI/uIt++NgGZnh85/a1DnXj6/bltZBRsAR1WdPT/cddthQvUHwVX7sSTKvqZly7e4TGaM7Ygv6L+PJ20+/yWZIhz1YrJqgGnkiUTzMBRaOAIPwutOwym8Ze2hLq56kd8a4T1VMh5sKhnPO3ONv4q6d+wk7Ie0AeaqZv6GSIBePOJ7vlGyTDX0AAKaehdJ22hNEywTvceJ5ej77Yof1/loAra8KdDSP86dXbbb40xZ6vOCyCx/wELTFGytIM2HCJNO9vUwSYuG/nI10VCqKMQ++sZMuOcSY0W3E/B11/s3wuww5wo+P2jhRo/MIFGOEIwAu3GD7RLE+H4LTudLDYsClLpoGyZIse7P+8iJUyzqJaG3hRIMdVtFn0NMdt7Ps2hof68rTDQj3bbhsHgl6G4aXvYO1TjglN7BLyBb4FhdUQa3sy/Dg+oRorCHoy4VO85Xx47aWA8KPkNATVdRrvDOFzATCx7VyGbs7G9hRzaOC55133EelsUoZ25ogz4qQr7tvyMI+t9lIT6I/ypB20pSCGkUI4yhyozl9YYmAozNS3/JNzpdsipPtvrsRUlFI50ig/onxhTg3AWN0XYnfB8uxBs=
