[package]
authors = ["Matt Dziuban <mrdziuban@gmail.com>"]
name = "sql-formatter"
version = "0.1.0"

[dependencies]
regex = "~0.2"
stdweb = { git = "https://github.com/koute/stdweb.git", rev = "9ba27f1c3" }
